# Generated by Django 3.2.25 on 2024-06-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20240608_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('comment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.productmodel')),
            ],
        ),
    ]
